### ISSUE TITLE
Beta4.1: Can't turn off NFC

### ISSUE THREAD

**Issue by p0izn** [Android-L-Porting-Team/Android-L-Mako#100]
Precondition: clean install, beta4.1., baseband 2.0.1701.02
1. Go to Settings, NFC & more
2. Uncheck NFC

Result: checkbox cannot be unchecked. Go to settings screen and return to NFC: NFC is on and keeps device awake.

**Comment by Sykopompos** [comment]
fixed in 4.2.2

**Comment by p0izn** [comment]
Edit: Closed
