### ISSUE TITLE
Black screen after end voice call

### ISSUE THREAD

**Issue by spirosun** [Android-L-Porting-Team/Android-L-Mako#101]
Issue with black screen.
1.Make a call to nexus - > end call
2.Screen is totally black but response so phone is not freezed.
3.Need to restart device to work again.

**Comment by spirosun** [comment]
BETA 4.1 and also on previous version

**Comment by p0izn** [comment]
Not confirmed. Clean installation of b4.1

**Comment by spirosun** [comment]
I make also clean installation, also checked with different configuration, I will add logcat soon

**Comment by spirosun** [comment]
07-22 08:26:43.080: V/Telephony(1104): GsmConnection: Update state from DISCONNECTED to DISCONNECTED for com.android.services.telephony.GsmConnection@b300859
07-22 08:26:43.080: V/Telephony(1104): GsmConnection: Update state from ACTIVE to DISCONNECTED for com.android.services.telephony.GsmConnection@15b9cf7
07-22 08:26:43.080: D/Telephony(1104): GsmConnection: mOriginalConnection new state = DISCONNECTED
07-22 08:26:43.081: D/TelecommFramework(1104): GsmConnection: setState: DISCONNECTED
07-22 08:26:43.081: D/TelecommFramework(1104): : Adapter set state CallService@3 DISCONNECTED
07-22 08:26:43.081: V/Telephony(1104): GsmConnectionService: recalculateConferenceState
07-22 08:26:43.081: D/Telephony(1104): GsmConnectionService: recalc - com.android.services.telephony.GsmConnection@15b9cf7
07-22 08:26:43.081: D/Telephony(1104): GsmConnectionService: recalc: active: false, is_conf: false, has_bkgd: false
07-22 08:26:43.081: D/TelecommFramework(1104): GsmConnection: Disconnected with cause 2 message null
07-22 08:26:43.082: D/TelecommFramework(1104): : Adapter set disconnected 2 null
07-22 08:26:43.083: I/Telecomm(1125): CallsManager: setCallState ACTIVE -> DISCONNECTED, call: [ACTIVE, com.android.phone/com.android.services.telephony.GsmConnectionService, ***********_]
07-22 08:26:43.084: I/screen_toggled(1268): 2
07-22 08:26:43.084: D/TelecommFramework(1104): GsmConnection: parenting com.android.services.telephony.GsmConnection@15b9cf7 to null
07-22 08:26:43.096: I/InCall(21546): InCallServiceImpl - updateCall: [InCall@4, parent:null, children:[]] => [InCall@4, DISCONNECTED, [Capabilities: HOLD ADD_CALL MUTE], children:[], parent:null]
07-22 08:26:43.096: I/InCall(21546): ProximitySensor - ProximitySensor{keybrd=0, dpad=0, offhook=1, hor=1, ui=1, aud=EARPIECE}
07-22 08:26:43.096: I/InCall(21546): ProximitySensor - turning on proximity sensor: already acquired
07-22 08:26:43.097: I/InCall(21546): InCallPresenter - Phone switching state: INCALL -> INCALL
07-22 08:26:43.097: I/screen_toggled(1268): 2
07-22 08:26:43.107: D/(187): csd_client_async_cb: msg_id 0x3e result 0 error 0
07-22 08:26:43.107: D/(187): csd_client_mic_mute: mute 0, state 2, rc 0
07-22 08:26:43.113: D/audio_hw_primary(187): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=1
07-22 08:26:43.114: E/BluetoothPhoneService(1104): Could not get a handle on Connection object for the call
07-22 08:26:43.117: I/screen_toggled(1268): 2
07-22 08:26:43.117: W/MessageQueue(1268): Handler (android.media.AudioPortEventHandler$1) {2a8e7bc6} sending message to a Handler on a dead thread
07-22 08:26:43.117: W/MessageQueue(1268): java.lang.IllegalStateException: Handler (android.media.AudioPortEventHandler$1) {2a8e7bc6} sending message to a Handler on a dead thread
07-22 08:26:43.117: W/MessageQueue(1268):   at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
07-22 08:26:43.117: W/MessageQueue(1268):   at android.os.Handler.enqueueMessage(Handler.java:631)
07-22 08:26:43.117: W/MessageQueue(1268):   at android.os.Handler.sendMessageAtTime(Handler.java:600)
07-22 08:26:43.117: W/MessageQueue(1268):   at android.os.Handler.sendMessageDelayed(Handler.java:570)
07-22 08:26:43.117: W/MessageQueue(1268):   at android.os.Handler.sendMessage(Handler.java:507)
07-22 08:26:43.117: W/MessageQueue(1268):   at android.media.AudioPortEventHandler.postEventFromNative(AudioPortEventHandler.java:166)
07-22 08:26:43.123: I/am_destroy_service(602): [0,663852323,2523]
07-22 08:26:43.126: D/audio_hw_primary(187): select_devices: out_snd_device(1: handset) in_snd_device(0: )
07-22 08:26:43.129: I/Telecomm(1125): PhoneStateBroadcaster: Broadcasted state change: IDLE
07-22 08:26:43.134: I/am_create_service(602): [0,813652512,.RepeatingService,10080,2523]
07-22 08:26:43.154: D/audio_hw_primary(187): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=1
07-22 08:26:43.155: I/art(2064): Heap transition to ProcessStateJankPerceptible took 23.317564ms saved at least -101KB
07-22 08:26:43.160: W/MessageQueue(1268): Handler (android.media.AudioPortEventHandler$1) {2a8e7bc6} sending message to a Handler on a dead thread
07-22 08:26:43.160: W/MessageQueue(1268): java.lang.IllegalStateException: Handler (android.media.AudioPortEventHandler$1) {2a8e7bc6} sending message to a Handler on a dead thread
07-22 08:26:43.160: W/MessageQueue(1268):   at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
07-22 08:26:43.160: W/MessageQueue(1268):   at android.os.Handler.enqueueMessage(Handler.java:631)
07-22 08:26:43.160: W/MessageQueue(1268):   at android.os.Handler.sendMessageAtTime(Handler.java:600)
07-22 08:26:43.160: W/MessageQueue(1268):   at android.os.Handler.sendMessageDelayed(Handler.java:570)
07-22 08:26:43.160: W/MessageQueue(1268):   at android.os.Handler.sendMessage(Handler.java:507)
07-22 08:26:43.160: W/MessageQueue(1268):   at android.media.AudioPortEventHandler.postEventFromNative(AudioPortEventHandler.java:166)
07-22 08:26:43.161: I/Telecomm(1125): CallServiceWrapper: Service unbound ComponentInfo{com.android.phone/com.android.services.telephony.GsmConnectionService}, from unbind.
07-22 08:26:43.177: I/am_destroy_service(602): [0,813652512,2523]
07-22 08:26:43.178: I/am_destroy_service(602): [0,907402019,1104]
07-22 08:26:43.179: I/Telecomm(1125): CallAudioManager: changing audio state from [CallAudioState isMuted: false, route; EARPIECE, supportedRouteMask: EARPIECE, SPEAKER] to [CallAudioState isMuted: false, route; EARPIECE, supportedRouteMask: EARPIECE, SPEAKER]
07-22 08:26:43.181: I/Telecomm(1125): InCallController: Unbinding from InCallService
07-22 08:26:43.182: I/am_destroy_service(602): [0,58448696,21546]
07-22 08:26:43.183: I/InCall(21546): InCallPresenter - Phone switching state: INCALL -> INCALL
07-22 08:26:43.188: I/am_create_service(602): [0,141512665,.RealTimeChatService,10055,5486]
07-22 08:26:43.196: I/InCall(21546): InCallPresenter - attemptCleanup? false
07-22 08:26:43.200: I/am_create_service(602): [0,479153566,.RepeatingService,10080,2523]
07-22 08:26:43.215: I/am_destroy_service(602): [0,141512665,5486]
07-22 08:26:43.219: I/am_destroy_service(602): [0,479153566,2523]
07-22 08:26:43.257: I/am_create_service(602): [0,954097791,.RepeatingService,10080,2523]
07-22 08:26:43.281: I/notification_enqueue(602): [10080,2523,com.rageconsulting.android.lightflow,1234556782,NULL,0,Notification(pri=2 contentView=com.rageconsulting.android.lightflow/0x1090070 vibrate=null sound=null defaults=0x0 flags=0x1 color=0x00000000)]
07-22 08:26:43.286: I/notification_enqueue(602): [10080,2523,com.rageconsulting.android.lightflow,1234556782,NULL,0,Notification(pri=2 contentView=com.rageconsulting.android.lightflow/0x1090070 vibrate=null sound=null defaults=0x0 flags=0x1 color=0x00000000)]
07-22 08:26:43.305: I/am_destroy_service(602): [0,954097791,2523]
07-22 08:26:45.097: I/InCall(21546): InCallPresenter - Hide in call UI: true
07-22 08:26:45.097: I/InCall(21546): InCallActivity - finish().  Dialog showing: false
07-22 08:26:45.098: I/am_finish_activity(602): [0,171475560,23,com.google.android.dialer/com.android.incallui.InCallActivity,app-request]
07-22 08:26:45.099: I/wm_task_moved(602): [1,1,0]
07-22 08:26:45.100: I/am_destroy_activity(602): [0,171475560,23,com.google.android.dialer/com.android.incallui.InCallActivity,finish-imm]
07-22 08:26:45.104: I/InCall(21546): InCallPresenter - attemptCleanup? false
07-22 08:26:45.105: I/InCall(21546): InCallPresenter - Phone switching state: INCALL -> NO_CALLS
07-22 08:26:45.127: D/AccelerometerListener(21546): enable(false)
07-22 08:26:45.132: I/InCall(21546): ProximitySensor - ProximitySensor{keybrd=0, dpad=0, offhook=0, hor=0, ui=1, aud=EARPIECE}
07-22 08:26:45.133: I/InCall(21546): ProximitySensor - turning off proximity sensor: releasing
07-22 08:26:45.138: W/qcom_sensors_hal(602): hal_acquire_resources, no active sensors!
07-22 08:26:45.143: I/InCall(21546): InCallPresenter - UI Destroyed)
07-22 08:26:45.144: I/InCall(21546): InCallPresenter - Phone switching state: NO_CALLS -> NO_CALLS
07-22 08:26:45.156: I/InCall(21546): InCallPresenter - attemptCleanup? true
07-22 08:26:45.156: D/AccelerometerListener(21546): enable(false)
07-22 08:26:45.171: I/sf_frame_dur(184): [com.google.android.dialer/com.android.incallui.InCallActivity,2368,1,1,0,1,1,0]
07-22 08:26:45.175: I/notification_panel_revealed(602): []
07-22 08:26:45.180: D/PhoneStatusBar(1268): disable: < expand ICONS_ alerts SYSTEM_INFO\* back home RECENT clock search >
07-22 08:26:45.190: I/wm_task_removed(602): [23,removeAppToken: last token]
07-22 08:26:45.190: I/wm_task_removed(602): [23,removeTask]
07-22 08:26:45.193: W/IInputConnectionWrapper(1145): showStatusIcon on inactive InputConnection
07-22 08:26:45.305: I/sf_frame_dur(184): [NavigationBar,18,0,0,0,1,0,0]
07-22 08:26:45.372: D/PhoneStatusBar(1268): disable: < expand ICONS alerts SYSTEM_INFO BACK\* HOME\* RECENT clock search >
07-22 08:26:46.762: D/ThermalDaemon(195): Sensor 'tsens_tz_sensor10' - alarm cleared 1 at 50.0 degC
07-22 08:26:46.763: D/ThermalDaemon(195): Sensor 'tsens_tz_sensor7' - alarm cleared 1 at 53.0 degC
07-22 08:26:46.763: D/ThermalDaemon(195): Sensor 'tsens_tz_sensor9' - alarm cleared 1 at 49.0 degC
07-22 08:26:47.139: D/audio_hw_primary(187): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=1
07-22 08:26:47.140: D/(187): csd_client_stop_voice: State 2
07-22 08:26:47.218: D/(187): csd_client_async_cb: msg_id 0x58 result 0 error 0
07-22 08:26:47.250: D/(187): csd_client_async_cb: msg_id 0x56 result 0 error 0
07-22 08:26:47.274: D/(187): csd_client_async_cb: msg_id 0x35 result 0 error 0
07-22 08:26:47.364: W/MessageQueue(1268): Handler (android.media.AudioPortEventHandler$1) {2a8e7bc6} sending message to a Handler on a dead thread
07-22 08:26:47.364: W/MessageQueue(1268): java.lang.IllegalStateException: Handler (android.media.AudioPortEventHandler$1) {2a8e7bc6} sending message to a Handler on a dead thread
07-22 08:26:47.364: W/MessageQueue(1268):   at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
07-22 08:26:47.364: W/MessageQueue(1268):   at android.os.Handler.enqueueMessage(Handler.java:631)
07-22 08:26:47.364: W/MessageQueue(1268):   at android.os.Handler.sendMessageAtTime(Handler.java:600)
07-22 08:26:47.364: W/MessageQueue(1268):   at android.os.Handler.sendMessageDelayed(Handler.java:570)
07-22 08:26:47.364: W/MessageQueue(1268):   at android.os.Handler.sendMessage(Handler.java:507)
07-22 08:26:47.364: W/MessageQueue(1268):   at android.media.AudioPortEventHandler.postEventFromNative(AudioPortEventHandler.java:166)
07-22 08:26:47.370: I/MediaFocusControl(602):  AudioFocus  abandonAudioFocus() from AudioFocus_For_Phone_Ring_And_Calls
07-22 08:26:48.323: I/art(2064): Heap transition to ProcessStateJankImperceptible took 20.082405ms saved at least 159KB
07-22 08:26:50.198: I/art(21546): Heap transition to ProcessStateJankImperceptible took 65.130476ms saved at least 3MB
07-22 08:26:53.438: I/PowerManagerService(602): Waking up from sleep...
07-22 08:26:53.447: D/SurfaceFlinger(184): Screen acquired, type=0 flinger=0xb8471508
07-22 08:26:53.544: I/DisplayManagerService(602): Display device changed: DisplayDeviceInfo{"Wbudowany ekran": 768 x 1280, 60.0 fps, density 320, 319.79 x 318.745 dpi, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
07-22 08:26:56.764: D/ThermalDaemon(195): Sensor 'tsens_tz_sensor8' - alarm cleared 1 at 50.0 degC
07-22 08:27:03.928: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:03.938: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:03.958: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:03.969: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:03.979: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:03.989: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:03.999: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.009: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.019: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.029: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.040: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.050: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.060: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.070: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.080: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.091: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.101: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.111: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.121: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.131: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.141: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.152: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:04.153: I/PowerManagerService(602): Going to sleep by user request...
07-22 08:27:04.153: I/power_sleep_requested(602): 0
07-22 08:27:04.154: I/PowerManagerService(602): Sleeping...
07-22 08:27:04.159: D/DisplayPowerController(602): Unblocked screen on after 10712 ms
07-22 08:27:04.169: D/SurfaceFlinger(184): Screen released, type=0 flinger=0xb8471508
07-22 08:27:04.348: D/SurfaceControl(602): Excessive delay in blankDisplay() while turning screen off: 189ms
07-22 08:27:04.349: I/DisplayManagerService(602): Display device changed: DisplayDeviceInfo{"Wbudowany ekran": 768 x 1280, 60.0 fps, density 320, 319.79 x 318.745 dpi, touch INTERNAL, rotation 0, type BUILT_IN, state OFF, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
07-22 08:27:06.602: I/PowerManagerService(602): Waking up from sleep...
07-22 08:27:06.609: D/SurfaceFlinger(184): Screen acquired, type=0 flinger=0xb8471508
07-22 08:27:06.704: I/DisplayManagerService(602): Display device changed: DisplayDeviceInfo{"Wbudowany ekran": 768 x 1280, 60.0 fps, density 320, 319.79 x 318.745 dpi, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
07-22 08:27:07.913: I/PowerManagerService(602): Going to sleep by user request...
07-22 08:27:07.913: I/power_sleep_requested(602): 0
07-22 08:27:07.913: I/PowerManagerService(602): Sleeping...
07-22 08:27:07.917: D/DisplayPowerController(602): Unblocked screen on after 1309 ms
07-22 08:27:07.917: D/SurfaceFlinger(184): Screen released, type=0 flinger=0xb8471508
07-22 08:27:08.098: D/SurfaceControl(602): Excessive delay in blankDisplay() while turning screen off: 180ms
07-22 08:27:08.098: I/DisplayManagerService(602): Display device changed: DisplayDeviceInfo{"Wbudowany ekran": 768 x 1280, 60.0 fps, density 320, 319.79 x 318.745 dpi, touch INTERNAL, rotation 0, type BUILT_IN, state OFF, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
07-22 08:27:09.091: I/PowerManagerService(602): Waking up from sleep...
07-22 08:27:09.102: D/SurfaceFlinger(184): Screen acquired, type=0 flinger=0xb8471508
07-22 08:27:09.197: I/DisplayManagerService(602): Display device changed: DisplayDeviceInfo{"Wbudowany ekran": 768 x 1280, 60.0 fps, density 320, 319.79 x 318.745 dpi, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
07-22 08:27:10.019: I/PowerManagerService(602): Going to sleep by user request...
07-22 08:27:10.019: I/power_sleep_requested(602): 0
07-22 08:27:10.019: I/PowerManagerService(602): Sleeping...
07-22 08:27:10.027: D/SurfaceFlinger(184): Screen released, type=0 flinger=0xb8471508
07-22 08:27:10.208: D/SurfaceControl(602): Excessive delay in blankDisplay() while turning screen off: 181ms
07-22 08:27:10.209: I/DisplayManagerService(602): Display device changed: DisplayDeviceInfo{"Wbudowany ekran": 768 x 1280, 60.0 fps, density 320, 319.79 x 318.745 dpi, touch INTERNAL, rotation 0, type BUILT_IN, state OFF, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
07-22 08:27:10.861: I/PowerManagerService(602): Waking up from sleep...
07-22 08:27:10.869: D/SurfaceFlinger(184): Screen acquired, type=0 flinger=0xb8471508
07-22 08:27:10.970: I/DisplayManagerService(602): Display device changed: DisplayDeviceInfo{"Wbudowany ekran": 768 x 1280, 60.0 fps, density 320, 319.79 x 318.745 dpi, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
07-22 08:27:11.783: I/PowerManagerService(602): Going to sleep by user request...
07-22 08:27:11.783: I/power_sleep_requested(602): 0
07-22 08:27:11.784: I/PowerManagerService(602): Sleeping...
07-22 08:27:11.791: D/SurfaceFlinger(184): Screen released, type=0 flinger=0xb8471508
07-22 08:27:11.968: D/SurfaceControl(602): Excessive delay in blankDisplay() while turning screen off: 178ms
07-22 08:27:11.969: I/DisplayManagerService(602): Display device changed: DisplayDeviceInfo{"Wbudowany ekran": 768 x 1280, 60.0 fps, density 320, 319.79 x 318.745 dpi, touch INTERNAL, rotation 0, type BUILT_IN, state OFF, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
07-22 08:27:14.002: I/PowerManagerService(602): Waking up from sleep...
07-22 08:27:14.009: D/SurfaceFlinger(184): Screen acquired, type=0 flinger=0xb8471508
07-22 08:27:14.104: I/DisplayManagerService(602): Display device changed: DisplayDeviceInfo{"Wbudowany ekran": 768 x 1280, 60.0 fps, density 320, 319.79 x 318.745 dpi, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
07-22 08:27:14.896: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:14.906: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:14.966: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:15.120: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:15.130: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:15.140: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:15.150: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:15.160: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:15.405: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:15.415: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:15.466: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:15.650: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:15.660: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:15.700: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:16.709: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:16.719: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:17.086: I/InputDispatcher(602): Dropped event because input dispatch is disabled.
07-22 08:27:17.093: I/PowerManagerService(602): Going to sleep by user request...
07-22 08:27:17.094: I/power_sleep_requested(602): 0
07-22 08:27:17.094: I/PowerManagerService(602): Sleeping...
07-22 08:27:17.097: D/DisplayPowerController(602): Unblocked screen on after 3089 ms
07-22 08:27:17.098: D/SurfaceFlinger(184): Screen released, type=0 flinger=0xb8471508
07-22 08:27:17.290: D/SurfaceControl(602): Excessive delay in blankDisplay() while turning screen off: 191ms
07-22 08:27:17.291: I/DisplayManagerService(602): Display device changed: DisplayDeviceInfo{"Wbudowany ekran": 768 x 1280, 60.0 fps, density 320, 319.79 x 318.745 dpi, touch INTERNAL, rotation 0, type BUILT_IN, state OFF, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
07-22 08:27:24.098: I/am_create_service(602): [0,328823414,.LightFlowService,10080,2523]
07-22 08:27:24.129: I/notification_enqueue(602): [10080,2523,com.rageconsulting.android.lightflow,1234556782,NULL,0,Notification(pri=2 contentView=com.rageconsulting.android.lightflow/0x1090070 vibrate=null sound=null defaults=0x0 flags=0x1 color=0x00000000)]
07-22 08:27:24.139: I/notification_enqueue(602): [10080,2523,com.rageconsulting.android.lightflow,1234556782,NULL,0,Notification(pri=2 contentView=com.rageconsulting.android.lightflow/0x1090070 vibrate=null sound=null defaults=0x0 flags=0x1 color=0x00000000)]
07-22 08:27:24.153: I/am_destroy_service(602): [0,328823414,2523]
07-22 08:27:34.093: W/BroadcastQueue(602): Timeout of broadcast BroadcastRecord{75304e4 u-1 android.intent.action.TIME_TICK} - receiver=android.app.LoadedApk$ReceiverDispatcher$InnerReceiver@3d0b1651, started 10002ms ago
07-22 08:27:34.093: W/BroadcastQueue(602): Receiver during timeout: BroadcastFilter{a16f7b7 u0 ReceiverList{322b5eb6 602 system/1000/u0 local:3d0b1651}}
07-22 08:27:34.093: I/am_broadcast_discard_filter(602): [0,122881252,android.intent.action.TIME_TICK,0,169277367]
07-22 08:27:35.940: I/DEBUG(182): invalid crash request of size 4 (from pid=1433 uid=0)
07-22 08:27:36.064: E/Sensors(9550): sns_fsa_la.c(386):fsa: fflush failed, 9
07-22 08:27:36.064: E/Sensors(9550): sns_fsa_la.c(386):fsa: fflush failed, 9
07-22 08:27:36.094: W/Sensors(9550): sns_smr_la.c(446):smr_la: smr_apps_la_thread_main is starting, fd=12, sns_smr.en_rx_msg_ptr=b70019d4
07-22 08:27:36.152: W/Sensors(9550): sns_sam_app.c(6827):sns_sam_reg_algo: Registering algo service 16, err 0
07-22 08:27:36.161: E/Sensors(9550): sns_debug_main.c(565):Debug Config File missing in EFS!

**Comment by spirosun** [comment]
ok, i've check it already and it was caused by Lighflow app ver 107.
Pushed logs to Reactle.
Thank You
