### ISSUE TITLE
No Gallery config window.

### ISSUE THREAD

**Issue by sagaceilo** [Android-L-Porting-Team/Android-L-Mako#102]
Hello,
When you try to go to config window in added today gallery2, there is black screen ( http://imgur.com/tJRwxa9).
Clean install, wiped Dalvik and cache.
Tried to reboot, but it doesn't make change, please, let somebody confirm this bug. 
// great work guys with this port !

**Comment by luis1997** [comment]
Same issue and cant print(i neves use it but...) (?

**Comment by Sykopompos** [comment]
The gallery2 is going to be removed in the next version, it is just a test pushing in some aosp stuff. Probably a missing aosp lib for it
