### ISSUE TITLE
Busybox not found 

### ISSUE THREAD

**Issue by Fast0n** [Android-L-Porting-Team/Android-L-Mako#105]
Busybox not found...
But with an app you can install, you could not enter into the system?
B4.2.7

**Comment by karishnu** [comment]
No busybox has not been inbuilt...

**Comment by Fast0n** [comment]
Really!! I know! When will be in serted in the build?

**Comment by Sykopompos** [comment]
Probably never. The port is exactly that, a port of the developer preview. It isn't a custom ROM nor is it meant to be

**Comment by Fast0n** [comment]
I understand. At this point you could also remove the SuperUser and create a zip with SU + Busybox

**Comment by Sykopompos** [comment]
That might not be a bad idea but I'm not sure about it. Busybox is easily installed from the market.
We were using koush's superuser since it played nice with selinux permissive while SuperSU didn't, that is fixed now so we can use either one

**Comment by Fast0n** [comment]
sorry I was not clear ... I meant if someone wanted the Root permissions to create a zip with inside superuser and Busybox. And leaving the ROM without root so the user can make their choice freely and not to force ...
