### ISSUE TITLE
LTE, Android L port, and tethering compatibility issues.

### ISSUE THREAD

**Issue by efraimbart** [Android-L-Porting-Team/Android-L-Mako#11]
Tethering works if either I don't have the LTE patch or I don't have the Android L port, but for some reason it doesn't work when both are together.

**Comment by Darex2094** [comment]
This is related to Android L Developer Preview Issue 48, which can be referenced here: https://code.google.com/p/android-developer-preview/issues/detail?id=48&q=tethering&colspec=ID%20Type%20Status%20Owner%20Summary

It has been accepted by the Google development team upstream and is being looked into. For now, tethering does not work at all.

@percy-g2 Please close as an upstream issue.
