### ISSUE TITLE
Home button issue.

### ISSUE THREAD

**Issue by thepiyushworld** [Android-L-Porting-Team/Android-L-Mako#112]
Currently on Beta 4.9 *
Phone hangs a lot as well as the touch pad is not responsive. "Home" button and "multi task" button as well as "back" button stopped working. Did a full factory wipe, still the same issue. 
Please help.

**Comment by Fast0n** [comment]
Download 4.9.1 and...
UPDATING
Put the latest mako-bla-bla.zip onto your Internal Storage
Reboot into Recovery (CWM/TWRP)
"wipe cache"
"advanced" -> "wipe dalvik cache"
"install zip" -> "install zip from sdcard" -> choose the [filename.zip] and confirm flashing procedure
"wipe cache"
"advanced" -> "wipe dalvik cache"
"reboot into system"
updating procedure may take up to 10 minutes - be patient

**Comment by thepiyushworld** [comment]
Same issue. 
I tried installing almost every update. Phone works fine when horizontally rotated. 
I guess it's the touch screen issue.

**Comment by Airhard** [comment]
i have the same proble i was on 3pre5 and on somer day it started to notwork...

**Comment by equiliym** [comment]
you can try using an app to replace the navbar.. im using ultimate dynamic navbar (udn), it hides stock one, hides itself giving you more space on screen and is customizable.. quite neat and working without problems for me..
