### ISSUE TITLE
Can't boot after first install.

### ISSUE THREAD

**Issue by vinayak-mehta** [Android-L-Porting-Team/Android-L-Mako#117]
I did a clean install using this build. https://github.com/Android-L-Porting-Team/Android-L-Mako/releases/tag/beta-4.9.1
After selecting 'reboot system now' in my CWM recovery, the phone is stuck in a loop at the screen which shows Google with the unlocked sign.

**Comment by thepiyushworld** [comment]
Try rebooting again in recovery and make sure you clear the cache as well as dalvik cache. 
If still the issue persists, Try installing  " 4.2.7 "

**Comment by AndersBerken** [comment]
I say: close this one
