### ISSUE TITLE
Location Issue: Changing mode.

### ISSUE THREAD

**Issue by sixlo** [Android-L-Porting-Team/Android-L-Mako#119]
Hi, I've got a problem when changing Location Mode from High Accuracy to Battery Saving for example. 

Even when you change that, mode stays on "High Accuracy" if you close Settings and go back to Location Menu.

**Comment by jecordei** [comment]
Which build are you running?

**Comment by Sykopompos** [comment]
I wish I could put in the tracker a sticky or something so these stop coming back. 

THIS IS A L BUG, NOT A PORT BUG
