### ISSUE TITLE
WIFI via proxy 

### ISSUE THREAD

**Issue by fgtmenow** [Android-L-Porting-Team/Android-L-Mako#12]
dont't work wifi with proxy settings (resources dont available)

add: it seems android dont't save proxy settings

**Comment by DJSubterrain** [comment]
This would be part of the static IP settings not being saved, no?

**Comment by Darex2094** [comment]
This is related to the official bugs 88 and 214 in which the L preview isn't saving static info or tunneling properly:

https://code.google.com/p/android-developer-preview/issues/detail?id=88&q=Type%3DDefect%20static%20ip&colspec=ID%20Type%20Status%20Owner%20Summary

https://code.google.com/p/android-developer-preview/issues/detail?id=214&q=Type%3DDefect%20proxy&colspec=ID%20Type%20Status%20Owner%20Summary

**Comment by Darex2094** [comment]
@percy-g2 This can be closed as it's 'an L problem' with the relevant info posted in my prior post.
