### ISSUE TITLE
Settings crashes..

### ISSUE THREAD

**Issue by vermaarjun7** [Android-L-Porting-Team/Android-L-Mako#122]
Whenever I open WiFi and type the credentials, a pop message  comes "Settings Crashed".

**Comment by Sykopompos** [comment]
Which credentials?

**Comment by vermaarjun7** [comment]
Wifi name and Password

**Comment by ima-monstaaa** [comment]
I would recommend a full wipe (Data, Dalvik, Cache, System), and then reflash the ROM.
