### ISSUE TITLE
advice FACEBOOK is fixed yeah!

### ISSUE THREAD

**Issue by luis1997** [Android-L-Porting-Team/Android-L-Mako#123]
Idk if because The lastest beta, but i justo updated Facebook and The comments issue its finally fixed!

**Comment by Sykopompos** [comment]
facebook should die!!!!!

**Comment by vincentimes** [comment]
Great ! I didn't even noticed !

**Comment by percy-g2** [comment]
wtf is this a issue?

**Comment by vincentimes** [comment]
Simply, we Facebook users, couldn’t see the comments due to some bug related to the Android L preview we installed on our Mako.

**Comment by percy-g2** [comment]
I know that but why spamming the issue tracker . posting in xda thread is enough

**Comment by vincentimes** [comment]
Fair enough. I was just +ing the fact that indeed it was resolved. In didn’t opened that issue.

**Comment by luis1997** [comment]
It was an advice, because to me and anothers The comments are fixed, everything is working righr
