### ISSUE TITLE
Android Wear Issues

### ISSUE THREAD

**Issue by philmacnevin** [Android-L-Porting-Team/Android-L-Mako#125]
I noticed a few issues using Android wear with the Android L Nexus 4 port:
- it displays music controls when listening to music in Google Play Music, but play / pause and skip track buttons do not work.
- when I use the command "start a timer for X minutes" it instead takes me to a screen to set an alarm

**Comment by Sykopompos** [comment]
that is because the android wear is not actually in the preview, the sdk came out after it so it is not fully functional
