### ISSUE TITLE
Mobile Data

### ISSUE THREAD

**Issue by Jagger15** [Android-L-Porting-Team/Android-L-Mako#127]
I am unable to use my mobile data
I can still make calls and such, just not browse the web from 4G/3G connections
WiFi is fine though

**Comment by fpMiguel** [comment]
Have you correctly configured the access point (settings)?

**Comment by Jagger15** [comment]
whoops lol, i had it set to LTE only
thanks XD

**Comment by alrekr** [comment]
Please close this issue.
