### ISSUE TITLE
NFC can't be disabled

### ISSUE THREAD

**Issue by patrickmaciel** [Android-L-Porting-Team/Android-L-Mako#129]
If I try uncheck NFC support, nothing happens... "check button" just brightened.

**Comment by Sykopompos** [comment]
I fixed that like 2 weeks ago

**Comment by patrickmaciel** [comment]
Sorry. I download that "L-port-Beta-4.9.99.9.9999.99.9 now with more 9s!!!!!" and this functionality not work.

Anyway, thanks.
Awesome rom.

**Comment by aurangzaib** [comment]
I can reproduce it. Go out of settings and then go again in NFC, then you can disable it
