### ISSUE TITLE
Camera locks up on capture, force closes, fails to connect on subsequent launches

### ISSUE THREAD

**Issue by glsignal** [Android-L-Porting-Team/Android-L-Mako#14]
When attempting to capture a still image, the camera locks up after tapping the shutter button and hangs before it can save the shot. After some attempts to interact with it, the app force closes and will no longer connect to the sensor on subsequent launches.

This is using beta 2, and apologies in advance if this is a known/solved issue on subsequent releases - I'm not keeping tabs on the XDA thread any more.

[Here's a `logcat | grep camera`](http://pastebin.com/vmR5qd7Q) too if it's relevant

**Comment by Dpat09** [comment]
Posted in second post of the thread and I was quoted but here you go. This isn't a Nexus 4 port issue btw I have a nexus 5 and its there too, it's been reported to the official L preview issue tracker so folks please do not create new entries there.. 

Workout/temp fix: go to Developer Settings then scroll down till you get to something called nuplayer. Disable it/ uncheck it and reboot. It should fix the issue.

**Comment by glsignal** [comment]
Gotcha, thanks for the info.

**Comment by ghost** [comment]
Disabling NU player doesn't fix it.

**Comment by Dpat09** [comment]
Okay please post a log cat, the general problems were fixed equity that simple workaround.
