### ISSUE TITLE
Google Play Services crashing while trying to login

### ISSUE THREAD

**Issue by kingracer** [Android-L-Porting-Team/Android-L-Mako#140]
When trying to login to Google account through some apps it just cycle crashing Gplay Services.

**Comment by luis1997** [comment]
same problem with MC5, leos fortune, real racing 3.....

**Comment by kingracer** [comment]
Are all that apps just crashing or crashing only when you trying to login via Google? Because I'm in second trouble

**Comment by kingracer** [comment]
Found fix - just need to re-enable sync in account settings >.<
