### ISSUE TITLE
Brightness slider

### ISSUE THREAD

**Issue by ConnorBaker** [Android-L-Porting-Team/Android-L-Mako#15]
I've noticed that the brightness slider makes no change once under the 20% or so mark of the slider. IE, dragging the brightness slider to the left will eventually stop changing the brightness level, even though there is stills space on the slider. It stops right around here, and shifting it further to the left makes no change.
![screenshot_2014-07-08-01-37-58](https://cloud.githubusercontent.com/assets/3880346/3505589/0b5abbf4-0662-11e4-8eb7-afe1290971cf.png)

Also, notice that the slider is cut off at the top and bottom. Perhaps the box is too small? Or is that just the design?

Warm regards,
Connor Baker

**Comment by ConnorBaker** [comment]
EDIT: This problem is caused with Adaptive Brightness. The brightness scales correctly without it ticked, but with it ticked display brightness scales to the minimum before the slider reaches the far left.

Warm regards,
Connor Baker

**Comment by benpye** [comment]
This is likely dependant on light level, it does work.
