### ISSUE TITLE
Problems with the safety pin of L

### ISSUE THREAD

**Issue by Fast0n** [Android-L-Porting-Team/Android-L-Mako#152]
I tried to put a safety pin in my phone but starts to buggare continuously

**Comment by JohnPeel** [comment]
You shouldn't be putting a safety pin in your phone. 
Unless you mean the sim card ejection tool, which the phone should be off when you're using.

**Comment by Fast0n** [comment]
I mean the pin in your phone NO IN SIM

**Comment by Sykopompos** [comment]
Very very very known L bug that you can't use a pin
