### ISSUE TITLE
Location Mode reverts to "High accuracy" if  "Battery saving" or "Device only" is chosen.

### ISSUE THREAD

**Issue by sebid** [Android-L-Porting-Team/Android-L-Mako#16]
STR:
1) Settings -> Location -> Mode
2) Toggle "Battery saving" or "Device only" mode. Notice it's toggled on.
4) Tap back or the back arrow key in the Location menu. Notice the Mode is the one previously selected.
5) Tap back again to exit the Location menu, back into Settings.
6) Enter Location again. Notice the Mode has defaulted to High accuracy.
7) Tap Mode, and notice that High accuracy is the selected toggle.

When selecting Device only, it may prompt with a Google Location consent.

https://gist.github.com/sebid/1739d7b0c9c9cb51dbfd

https://www.youtube.com/watch?v=DmGgGvvSP1Y

Beta 2 preview ( 492f5cdbdb0ed67052ab2ecdf5633d64 ). Will retest on Beta 3, though I haven't seen any location fixes on the tracker.

**Comment by RealSlimShadyMC** [comment]
This is an issue with the offial google code as well.

**Comment by benpye** [comment]
Closing as this is an upstream issue.
