### ISSUE TITLE
Can not receive MMS

### ISSUE THREAD

**Issue by davidcd13** [Android-L-Porting-Team/Android-L-Mako#23]
I can send MMS but I can not receive.

**Comment by Darex2094** [comment]
Seconding. It's a known issue with L / Hangouts, linking to here for the original bug report:

http://forum.xda-developers.com/showpost.php?p=53987943&postcount=1309

According to dziegmangpf of the Google Community Management Team, it's been passed to the Hangouts team as a Hangouts issue, though, which doesn't make sense as everything was fine in Hangouts prior to L, though I didn't check if there was a bump in revision number on Hangouts.

**Comment by davidcd13** [comment]
OK. thank you for the information 😃.

**Comment by Darex2094** [comment]
It's worth noting that the official tracker states some have had luck with HelloSMS as it uses an independent APN setup from the rest of Android. It's also worth noting that some have reported disconnecting from wifi/mobile and reconnecting forces it to attempt the download and succeeds, though it hasn't worked for me. YMMV

**Comment by Darex2094** [comment]
According to http://forum.xda-developers.com/showpost.php?p=53998385&postcount=1547

Remove the Hangouts.apk and reinstall it from the Play Store, being sure to set up the proper APN. For him that resolved the issue

EDIT: Nope, still hangs for me

**Comment by ghost** [comment]
Well, it works for me with only those modifications. 
I opened setup, sms then apn at the very bottom, click on the apn I didn't use but not on the one I want to use and it work.
The strange thing is that when I click on the apn, they disapeared...

I'm on beta 3 preview 3

**Comment by benpye** [comment]
Closing as this is an upstream issue.
