### ISSUE TITLE
VPN speed is too slow

### ISSUE THREAD

**Issue by mymbrooks** [Android-L-Porting-Team/Android-L-Mako#24]
I used both android vpn settings and Astrill VPN app.The speed is too slow.When I used Android 4.4.4 last day, the VPN speed is good.

**Comment by Darex2094** [comment]
It appears to be related to issue 214 in the official tracker, linked below:

https://code.google.com/p/android-developer-preview/issues/detail?id=214&q=Type%3DDefect%20VPN&colspec=ID%20Type%20Status%20Owner%20Summary

In my own testing, I also receive very slow tunneling and eventual reboot. This is an L issue and has been passed on upstream.

Steps to reproduce:
1) Set up a VPN tunnel
2) ....
3) Bacon

**Comment by ion-storm** [comment]
Not experiencing this on Private internet access VPN:
Check out my Ookla Speedtest result. What's your speed? http://www.speedtest.net/my-result/a/886346397

**Comment by benpye** [comment]
Closing as this is an upstream issue.
