### ISSUE TITLE
Lock screen

### ISSUE THREAD

**Issue by renansalgado** [Android-L-Porting-Team/Android-L-Mako#25]
When the phone is locked, the screen never turns off by itself.

**Comment by luis1997** [comment]
verify that the neve sleep option in dev options is off, and the screen off time its rasonable...

**Comment by renansalgado** [comment]
the neve sleep option in dev options is off and the screen off time is 1 minute.

**Comment by renansalgado** [comment]
I solved the problem! It's a bug related to app "Knock Lock". When it is activated not let the screen off. I guess that did not happen in Beta 1 ..

**Comment by Darex2094** [comment]
Confirming it's an app issue. Tested and was able to reproduce the result.

Steps to Reproduce:
1) Install Knock Lock
2) ....
3) Bacon

**Comment by benpye** [comment]
Closing as isn't a ROM issue.
