### ISSUE TITLE
Mobile tethering broken.

### ISSUE THREAD

**Issue by RealSlimShadyMC** [Android-L-Porting-Team/Android-L-Mako#29]
I can start the tethering deamon and it broadcasts, but packets don't get routed through my phone, and instead get stuck.

**Comment by Darex2094** [comment]
This is a duplicate of #11

**Comment by RealSlimShadyMC** [comment]
Is the LTE patch built into the ROM? I'm just using the normal radio

**Comment by Darex2094** [comment]
It isn't necessarily a problem with LTE as much as it's a routing and tunneling issue. It affects tethering, VPN tunneling, etc.

**Comment by benpye** [comment]
Closed as duplicate of #11 .
