### ISSUE TITLE
Hotword Detection

### ISSUE THREAD

**Issue by beinghuman23** [Android-L-Porting-Team/Android-L-Mako#30]
'Ok Google' not working anywhere

**Comment by Darex2094** [comment]
Just to be sure, do you have it enabled? You can check that by going to the Google Now side of the launcher (swipe left on the home screen), going to the bottom, hitting the three dots, going to Voice,  and clicking Ok Google Detection.

Keep in mind you have to use the Google Now launcher, not third party launchers, though some are starting to support it.

If it is enabled, what revision of the ROM are you using so I can test it? I just checked my phone and it's working, which is running Beta 2

**Comment by beinghuman23** [comment]
i m running beta 3, and i checked all possible things to get it work but its not working...

**Comment by beinghuman23** [comment]
Well found a way...just changed the language in setting it worked...

**Comment by Darex2094** [comment]
Got me in the middle of typing :P Yes, in Beta 3 Preview 3 I was able to reproduce a pronounced lag in hotword detection right out of the flash. Disabling and reenabling detection didn't change the delay (we're talking over a minute before the home screen reacted to the hotword with no sleep in between), but changing the language pack for some reason did the trick. I don't know if it had to do with reinitializing the English pack or what...

**Comment by Darex2094** [comment]
I wouldn't necessarily mark this as closed as it's still technically a bug, though creating a new label, something like 'Workaround' to keep it visible and let others know that there's a workaround posted, but it isn't resolved at the ROM level, would be more advisable.

Just my $0.02

@percy-g2 

Another suggestion might be an L Bug label to clearly indicate what's an L-based bug and not a ROM bug once something is closed. Again, just my $0.02

**Comment by percy-g2** [comment]
Hotword Detection everywhere is not related to port and it's workaround's can be found on xda and on google search.
Google is releasing it's bug fixed google search updates ,check them out .

**Comment by Darex2094** [comment]
I don't... feel like that's related. So far as I can tell Beta 2 and Beta 3 are using the same launcher, and in Beta 2 hotword detection didn't have any issues at all, though in Beta 3 you seem to have to reset the language pack to get it to work reliably. That doesn't shout "Google Now" problem to me, considering the two builds are using the same build of Google's launcher.

Workarounds for this issue don't necessarily relate to my suggestion, either, which is a more broad approach for handling these kinds of bug reports in the future.

Again, just my $0.02 -- Your effort will go wherever you place value.
