### ISSUE TITLE
new feature peripheral of android l bluetooth ble got an advertisement error while advertising.

### ISSUE THREAD

**Issue by melochale** [Android-L-Porting-Team/Android-L-Mako#35]
I'm based on lpv-79-mako-port-beta3-pre3.zip package, my test app implement the official api related peripheral mode, but it can't work well with nexus 4 on android L, i.e. the AdevertiseCallback class's onFailure function got error code 5(public static final int ADVERTISE_FAILED_CONTROLLER_FAILURE Operation fails due to bluetooth controller failure.Constant Value: 5 (0x00000005)), which means we can't broadcast any advertisement, but the same app runs well on nexus 5, hum, strange!

**Comment by zhangwm1219** [comment]
I am facing the same problem,I get some infomation that Android devices can now function in Bluetooth Low Energy (BLE) peripheral mode. Apps can use this capability to broadcast their presence to nearby devices from New in Android L.I'm making an application about this,When I started to startAdvertising,I get the same error code.and  I get the logcat(Adreno-GSL,<ioctl_kgsl_device_getproperty:663>: mmap failed: errno 22 Invalid argument)

**Comment by Darex2094** [comment]
This could be related to Issue 605 on the official Google bugtracker, referencable here: https://code.google.com/p/android-developer-preview/issues/detail?id=605&q=bluetooth&colspec=ID%20Type%20Status%20Owner%20Summary

It's been reported and may be related to your issue, though it hasn't been accepted by the Google team yet upstream.

**Comment by Darex2094** [comment]
Actually, let me reference Issue 72862 which has been assigned by the Google dev team: https://code.google.com/p/android/issues/detail?id=72862

Looks like it's known upstream and is being looked at

@percy-g2
