### ISSUE TITLE
camera and battery not charging issues

### ISSUE THREAD

**Issue by dega123** [Android-L-Porting-Team/Android-L-Mako#39]
it says camera cant be opened after taking a snap and it stucks there..need to reboot to open the camera again..
battery doesnt charge from 46% onwards..it says its charging but it just stucks there..
please fix :) cheers

**Comment by percy-g2** [comment]
please read flashing instructions carefully and follow them .

**Comment by dega123** [comment]
thankyou..its working after flashing again..
