### ISSUE TITLE
 miscellaneous take lot's of battery

### ISSUE THREAD

**Issue by alivelee** [Android-L-Porting-Team/Android-L-Mako#4]
In battery section,the miscellaneous take most of the usage and keep the phone awake

**Comment by die2mrw007** [comment]
Misleading title

**Comment by alivelee** [comment]
I think that the nfc service keep the phone awake

**Comment by die2mrw007** [comment]
You can turn it off safely :)

**Comment by alivelee** [comment]
update to beta 3 solved it
