### ISSUE TITLE
Static IP adress change to DHCP

### ISSUE THREAD

**Issue by zakk87** [Android-L-Porting-Team/Android-L-Mako#40]
Hi, I'm using static IP adress and I have problem. When I turn off and turn on WiFi static adress in remembered SSID changing to DHCP.

First connection with Static IP
![screenshot_2014-07-07-14-44-57](https://cloud.githubusercontent.com/assets/8110481/3520428/dfe1405a-072f-11e4-8461-ef498f3fdfa0.png)

After turn off and turn on a WiFi
![screenshot_2014-07-07-14-45-36](https://cloud.githubusercontent.com/assets/8110481/3520429/dfe5a9e2-072f-11e4-99a0-64f6f368aff4.png)
![screenshot_2014-07-07-14-45-57](https://cloud.githubusercontent.com/assets/8110481/3520430/dfe9f132-072f-11e4-972b-d33fc00652c2.png)

Here's a logcat http://pastebin.com/8t964Hyx

**Comment by percy-g2** [comment]
https://code.google.com/p/android-developer-preview/issues/detail?id=88&colspec=ID%20Type%20Status%20Owner%20Summary
