### ISSUE TITLE
gallery preview panel in camera

### ISSUE THREAD

**Issue by zakk87** [Android-L-Porting-Team/Android-L-Mako#41]
like on screenshot. I have panel from gallery on camera preview.
![screenshot_2014-07-07-12-09-52](https://cloud.githubusercontent.com/assets/8110481/3520458/67c98fcc-0730-11e4-8c0b-7a5b9285d2e8.png)

**Comment by percy-g2** [comment]
it's not an issue

**Comment by zakk87** [comment]
So it's a new feature from uncle G*?
roger that
