### ISSUE TITLE
no contact photo incoming calls

### ISSUE THREAD

**Issue by zakk87** [Android-L-Porting-Team/Android-L-Mako#42]
When I receive a call the person's picture sometimes doesn't show. But sometimes blink for a second before dissapear. Can you look at it?
Best regards.

**Comment by Darex2094** [comment]
I can't reproduce this bug on incoming calls. Which build are you using?

**Comment by Darex2094** [comment]
Apparently it actually is an issue and it's being looked at by Google as a defect in the L preview: https://code.google.com/p/android-developer-preview/issues/detail?id=305&q=contact%20image&colspec=ID%20Type%20Status%20Owner%20Summary

@percy-g2

**Comment by zakk87** [comment]
I'm using beta3 p3. Thanks for the link.
