### ISSUE TITLE
Broken 2G/3G switch in menu

### ISSUE THREAD

**Issue by zakk87** [Android-L-Porting-Team/Android-L-Mako#43]
I can't switch 3G signal to 2G. In work I don't have a signal so I must switch to other 2G operator. Changing preffered network type don't work also in menu from dialer _#_#INFO#_#_ Can you fix network mode? Thanks for your hard work.

**Comment by percy-g2** [comment]
https://github.com/Android-L-Porting-Team/Android-L-Mako/issues/6
