### ISSUE TITLE
French Charging UI crash

### ISSUE THREAD

**Issue by Guillaume351** [Android-L-Porting-Team/Android-L-Mako#47]
When the device is in French, the UI crash in loop until you unplug device. I don't have this problem when I switch to English.

**Comment by AlexandreKueny** [comment]
I have the same problem. I posted a message yesterday but I did not try to change the language. Switch  to English actually fix the problem for me too.

**Comment by iazone** [comment]
+1, Only in French

**Comment by Darex2094** [comment]
Verifying as well that it's only in French. Related to Issue 82 on the official Google bugtracker for the L developer preview, referencable here: https://code.google.com/p/android-developer-preview/issues/detail?id=82&q=french&colspec=ID%20Type%20Status%20Owner%20Summary

The official Google development team has accepted the bug and are looking into it upstream.

@percy-g2
