### ISSUE TITLE
Google Chrome

### ISSUE THREAD

**Issue by SlayerOrnstein** [Android-L-Porting-Team/Android-L-Mako#50]
![screenshot_2014-07-09-19-26-36 1](https://cloud.githubusercontent.com/assets/6075693/3532681/077c2b3e-07c1-11e4-82a3-b022f836f2a2.png)
![screenshot_2014-07-09-19-29-12 1](https://cloud.githubusercontent.com/assets/6075693/3532685/12c8d8f2-07c1-11e4-9757-085bc85a25d8.png)

Chrome seems to freeze with graphical errors like black blocks on webpage

**Comment by ConnorBaker** [comment]
Was this a full wipe? I haven't had this issue.
- Connor Baker

**Comment by SlayerOrnstein** [comment]
yeah full wipe the only thing added was  faux kernel 40m

**Comment by ion-storm** [comment]
This only happens with faux kernel, not the stock kernel, only reason I know this is because I use faux kernel.  Until we have kernel source use stock kernel and you won't have this issue.
