### ISSUE TITLE
Port sucks

### ISSUE THREAD

**Issue by Sykopompos** [Android-L-Porting-Team/Android-L-Mako#51]
This port sucks and I want my money back

**Comment by percy-g2** [comment]
+1

**Comment by Kotpes** [comment]
You suck

**Comment by benpye** [comment]
Yeah, can confirm, terrible port.

**Comment by gbyers** [comment]
It's free YOU HAVE NO RIGHT TO COMPLAIN ;)

**Comment by Sykopompos** [comment]
I can do whatever I want and it wasn't free for me!!!

**Comment by die2mrw007** [comment]
Hey, you should sucks justin bieber's dick bro

**Comment by Sykopompos** [comment]
Not sure if troll or not.... Or doesn't realize that I was trolling my team mates

**Comment by marciogomes** [comment]
Hahahaha

**Comment by percy-g2** [comment]
enough lulzzz
