### ISSUE TITLE
PIN Lock Issues

### ISSUE THREAD

**Issue by cybermatatu** [Android-L-Porting-Team/Android-L-Mako#52]
The lock constantly locks the phone when you try to unlock it. This happened where PIN lock security is enabled

**Comment by benpye** [comment]
This sounds like it might be an Android L issue.

**Comment by AndersBerken** [comment]
I have the exact same problem. Re-boot the phone does resolve it. But returns again after approx halv-1day.

**Comment by mattjanicki** [comment]
_This_ sounds like that L bug mentioned in the other bug report.  Probably not port-related. http://pocketnow.com/2014/07/08/android-l-as-your-daily-driver

> Last, but certainly not least, is a particularly frustrating bug. I have to use a PIN or password lockscreen with my corporate Exchange account. Sometimes when I unlock with my PIN, the phone unlocks, then immediately locks again. I’ll input the PIN again, and again it will unlock, and immediately re-lock. Over and over and over.
> 
> To escape this quagmire of PIN screens I have to shut down my phone and reboot. After that it’s not a problem, unlocking works the way it’s supposed it.

**Comment by AndersBerken** [comment]
So, cant be fixed unless Google fix it?
