### ISSUE TITLE
first boot - automatically connect to mobile internet

### ISSUE THREAD

**Issue by jagoo** [Android-L-Porting-Team/Android-L-Mako#58]
On the first boot in setup guide, where is chosen language, wifi connection etc. it is automatically connect to mobile internet over GPRS/EDGE/3G/HSDPA/LTE. I don't use mobile internet, I am using only wifi but if I connect to mobile internet (unwanted) I must pay for it once for the day.

Can you please set in ROM to don't connect to mobile internet and wait for wifi connection? I think that it is set in some Android ROMs.

Anyway thanks for your hard work.

**Comment by RealSlimShadyMC** [comment]
This is based off of stock, I don't think any custom ROM options at all. This is a developer preview, not an Android junkie's playground. Wait for an official release or go back to kk

**Comment by percy-g2** [comment]
don't put your sim inside on first boot simple
