### ISSUE TITLE
some have problems mobile network

### ISSUE THREAD

**Issue by minhbi245** [Android-L-Porting-Team/Android-L-Mako#6]
I can't turn off or turn on NFC, so that make battery not good and mobile network can't switch 3G to 2G

**Comment by die2mrw007** [comment]
Which version of the release you using. It has been addressed in beta 3 release. 

Just go back from nfc option page to settings and visit back.. Then try changing and it will work

**Comment by minhbi245** [comment]
OK, thanks a lot. In preview beta3 can fix NFC but about mobile network can't be change 3G to 2G. Everything is OK. Thanks developers

**Comment by die2mrw007** [comment]
Turning off nfc is possible with even in beta 2 release and for 3g mode to 2g mode shift, yes there is an issue which is already been addressing.

**Comment by minhbi245** [comment]
Thanks listen my comment. I hope you will fix it soon, that's all right!

**Comment by percy-g2** [comment]
Issue title edited :- Removed NFC as it's working

**Comment by Kevindeving** [comment]
Remove persist.radio.mode_pref_nv10=1 from build.prop bacuse it should read network mode from modem and not NV.

**Comment by percy-g2** [comment]
confirmed @Kevindeving . Send a pull request
