### ISSUE TITLE
Audio is lagging on Chromecast

### ISSUE THREAD

**Issue by supreme7** [Android-L-Porting-Team/Android-L-Mako#60]

**Comment by percy-g2** [comment]
provide logcat

**Comment by supreme7** [comment]
https://www.dropbox.com/sh/vv6wd7e5cbulmd2/AAA7lrfHMROG7aVf_3Ey0CAfa/2014-07-11-16-04-51.txt

**Comment by Bigbossradio** [comment]
I just checked it out with my chromecast and youtube and found no "Lag" it worked fine

**Comment by SebastianPuszies** [comment]
sound is lagging while screen mirroring
