### ISSUE TITLE
Dialer bug

### ISSUE THREAD

**Issue by luis1997** [Android-L-Porting-Team/Android-L-Mako#64]
I don't know if it randomly or just me but i went to do a call and number 7 was a S not the number

**Comment by Sykopompos** [comment]
L Bug

**Comment by percy-g2** [comment]
explain the issue with details

**Comment by luis1997** [comment]
The number 7 in The dialers a letter "S" not The number 7

**Comment by percy-g2** [comment]
http://s3.postimg.org/676q0dreb/Screenshot_2014_07_12_19_34_55.png

**Comment by luis1997** [comment]
http://s2.subirimagenes.com/imagen/previo/thump_8991250screenshot2014071211.png

**Comment by percy-g2** [comment]
which language are you using?

**Comment by luis1997** [comment]
Spanish, maybe its randomly, it works in The screen appears like 7 its just in The dialer,(beta3 preview 5)

**Comment by percy-g2** [comment]
change the language to English and reboot .

**Comment by luis1997** [comment]
All right  its a spanish(spain) bug in spanish (usa) works, can be fixed?

**Comment by percy-g2** [comment]
It's translation issue wait for Official release by google .

**Comment by luis1997** [comment]
OK, i don't care i never use it, thanks
