### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by roblesedu** [Android-L-Porting-Team/Android-L-Mako#68]
My device has an error - E: Error in / sdcard/0/Downloads/lpv-79-mako-port-beta3-pre5.zip (Status 7). Why?

**Comment by Fast0n** [comment]
Error in downloading! 

I apologize for the Inglese translation

**Comment by Darex2094** [comment]
It's possible that the downloaded ZIP is corrupt somehow. Preview 5 works fine for me as well as many others, so that'd be where I'd start looking. Make sure you download it on a stable connection and, if you'd like, compare the MD5 when it's done.

**Comment by Fast0n** [comment]
It happened to me as well for this, I suggest you download it again.

I apologize for the Inglese translation

**Comment by psycho693** [comment]
What recovery are you using? And is it the latest version?

**Comment by roblesedu** [comment]
ClockworkMod Recovery v6.0.1.9
