### ISSUE TITLE
lock screen

### ISSUE THREAD

**Issue by ryanwng12** [Android-L-Porting-Team/Android-L-Mako#7]
No lock screen at all in the settings I set the lock screen to slide but when I turn the screen on no lock at all...

**Comment by eth0izzle** [comment]
I have the same issue but with all lock screen types, not quite sure how to debug it.

**Comment by ryanwng12** [comment]
Any help??

**Comment by Nephrited** [comment]
All lock screen types are working here on a clean flash of beta 2. The "slide" lock type looks like this:
![7ymioyv](https://cloud.githubusercontent.com/assets/6793135/3510395/55c372dc-06a6-11e4-9668-338fd969af8a.png).

@Ryan1222 - I don't want to be too harsh on you here, but you've posted a three bugs and a number of consecutive comments that all suggest you haven't researched what it exactly is you are installing. The L release is unstable, and shouldn't really be used if all you're interested in is having the newest version of Android before everyone else.

**Comment by eth0izzle** [comment]
Can confirm a fresh install fixes this, for me at least.

**Comment by ryanwng12** [comment]
I'm sorry for giving you all the hassle.. I mean it and thank you for every guide. It was my fault :)
