### ISSUE TITLE
Charging problem

### ISSUE THREAD

**Issue by Jonathanlg59** [Android-L-Porting-Team/Android-L-Mako#75]
When the device is charging no way to use the system in French, only when it is disconnected. No problem in English. Sorry for my bad english

**Comment by vincentimes** [comment]
Same here, any clues guys ?

**Comment by anujthapar** [comment]
I am feeling no charging problem in beta 3 rev 5

**Comment by sigeln** [comment]
I have the same problem: when charging, no way to use the phone once it's locked. The "Charging" (in french) is displayed, but when it's supposed to display the charging time, the device can't be used anymore until it's disconnected.

**Comment by Jonathanlg59** [comment]
Even v5 beta 3 still the same problem in French. The product is in French when load

**Comment by nox-321** [comment]
https://code.google.com/p/android-developer-preview/issues/detail?id=82&q=french&colspec=ID%20Type%20Status%20Owner%20Summary

Android L Preview problem, should be fix in final release. Bug already submitted and closed (#47)

Switch your phone to English or flash KitKat back to avoid this.

Please close this issue.
