### ISSUE TITLE
Keyboard Vibration

### ISSUE THREAD

**Issue by mycrof7** [Android-L-Porting-Team/Android-L-Mako#77]
keyboard is not vibrating

**Comment by mycrof7** [comment]
+when i plug usb cable to pc + n4 it does vibrate
 when i remove the cable it doesnt vibrate...

**Comment by jecordei** [comment]
Make sure you don't have 'Do Not Disturb' enabled.

**Comment by mycrof7** [comment]
its not enabled

**Comment by dvpradhan** [comment]
Keyboard vibration is not available if the battery saver mode is ON.

**Comment by mycrof7** [comment]
ok! it was abiut battery saver. sorry.
