### ISSUE TITLE
After call and lock the phone,then the phone could not unlock

### ISSUE THREAD

**Issue by ruikaka16** [Android-L-Porting-Team/Android-L-Mako#78]
I have flashed the beta,but when i locked the phone after the call,the phone could not unlock, pressed the power button did not respond.I am not sure whether this is a bug,is there anyone have the same issue?

**Comment by ruikaka16** [comment]
Finally,i found that the problem was caused by the application named lightflow which may be conflict with the system.When i uninstall it,the issue was fixed.

**Comment by nox-321** [comment]
As it's not a bug, I think you could close this issue.
