### ISSUE TITLE
Release beta 4 changes MAC address of the device

### ISSUE THREAD

**Issue by mammenj** [Android-L-Porting-Team/Android-L-Mako#79]
Beta 4 release changes the MAC address of the device. As a result, users using MAC address filtering in the router will not get connected to WiFi.

**Comment by mammenj** [comment]
It actually does not change it, but it does not read from the .macaddr file but assigns a default dummy mac address, which would be same for all device

**Comment by denislets** [comment]
I also confirm this issue on Beta 4.

**Comment by Sykopompos** [comment]
Fixed in 4.1
