### ISSUE TITLE
couldn't pull down notification bar

### ISSUE THREAD

**Issue by ryanwng12** [Android-L-Porting-Team/Android-L-Mako#8]
I pulled the bar but the notification part works but the quick setting doesnt ...

**Comment by die2mrw007** [comment]
It is happened only at the first boot one time google sign in and restore operstion. After that it should work. This behaviour is same with even Kitkat, Jellybean and prior releases.

**Comment by ryanwng12** [comment]
What do you mean? How do I fix it?

**Comment by ryanwng12** [comment]
Should I flash it again?
