### ISSUE TITLE
supersu 2.01 installation problem

### ISSUE THREAD

**Issue by anujthapar** [Android-L-Porting-Team/Android-L-Mako#83]
i used google play to flash supersu in beta3 rev 5 which the rom downloaded but failed to install. Later i used root explorer to flash downloaded supersu 2.01 Which was also a failure.

**Comment by jecordei** [comment]
Make sure that you do not have Superuser already installed on your phone as I had this issue happen to me already.

**Comment by anujthapar** [comment]
Beta3revision5 has already inbuilt root apk

**Comment by karishnu** [comment]
Try SuperSU 2.02... Has fixed the selinux problem....

**Comment by anujthapar** [comment]
Let me check

**Comment by anujthapar** [comment]
Its working problem solved. Thanks.
