### ISSUE TITLE
WIFI - Static IP settings not saved

### ISSUE THREAD

**Issue by yvrRome** [Android-L-Porting-Team/Android-L-Mako#89]
When I set the static IP settings, they get used for the initial connection but they're not saved. If I try to modify settings, it is set back to dhcp. So if I turn off WiFi and back on again, it uses dhcp.

Tested on Beta 4.

**Comment by syedtalha** [comment]
Same here. Problem seems with WiFi driver rather than OS, since this works fine with Nexus 7 and 5

**Comment by nox-321** [comment]
Referring to #40 :

https://code.google.com/p/android-developer-preview/issues/detail?id=88&colspec=ID%20Type%20Status%20Owner%20Summary

Android Preview specific problem, you should close issue.
