### ISSUE TITLE
home button

### ISSUE THREAD

**Issue by ryanwng12** [Android-L-Porting-Team/Android-L-Mako#9]
Home button doesn't work

**Comment by ghost** [comment]
Seems basics are out... which version?

**Comment by die2mrw007** [comment]
It should work. Try beta 2 release

**Comment by greyivy** [comment]
Dirty flash?

**Comment by ion-storm** [comment]
I'm closing this issue, this happens with dirty flashes and sometimes the device doesn't provision correctly a full wipe fixes this

**Comment by ryanwng12** [comment]
I wiped all cache and flashed it correctly...

**Comment by Nephrited** [comment]
Did you correctly follow the first time flashing steps?
1. Put the file onto your Internal Storage
2. Reboot into Recovery (CWM/TWRP]
3. "wipe data/factory reset"
4. "mounts and storage" -> "format system"
5. "advanced" -> "wipe dalvik cache"
6. "install zip" -> "install zip from sdcard" -> choose the
   mako-bla-bla-zip and confirm flashing procedure
7. "wipe cache"
8. "advanced" -> "wipe dalvik cache"
9. "reboot into system"
10. _first boot may take up to 10 minutes - be patient_

There are 5 individual wipes there.

**Comment by ryanwng12** [comment]
I am flashing this from another ROM.. How to flash if I'm updating?

**Comment by ryanwng12** [comment]
BTW I'm flashing beta 2
