### ISSUE TITLE
Cannot connect to WIFI on Beta v4.1 and Beta 4.2.2

### ISSUE THREAD

**Issue by namzo** [Android-L-Porting-Team/Android-L-Mako#96]
Hi guys,
I can't connect to WIFI on Beta v4.1. 

Edit: The phone doesn't detect the WIFI connection. It used to work on Beta 3 Preview 5.

Thanks

**Comment by user858753257** [comment]
sorry for you, but for me it works perfectly . Have you deleted your known wifi stations ?

**Comment by anujthapar** [comment]
Nonsense post as its working on mine also

**Comment by namzo** [comment]
@F3000 Yeah I already did that. I though it was as a result of the update. I just upgraded from Beta 3 Preview 5 and it worked then. Thanks anyway.. I'll figure it out.

**Comment by namzo** [comment]
@F3000 @anujthapar:
So I confirmed & I'm not crazy.. The issue still exists even in the new beta 4.4.2 release. So, I clean flashed "Beta3 Pre5" to be sure, and it worked.
My phone is unable to detect my WIFI (2.4GHz, WPA2, Channel 11) on Beta v4.1 and above.

**Comment by Sykopompos** [comment]
Nothing on that was changed but it might be a configuration file line that was not edited. Any other kernel used on 4.1 or 4.2.2 will counter the issue as it is a bug in the kernel source that was added in for b4

**Comment by anujthapar** [comment]
Actually these problem are result of old recovery flash problems. Better update recovery files. When in one flash of new version on old version shows error better flash new rom at least 2-3 times and wipe cache and dalvik cache.

**Comment by namzo** [comment]
It works now!! I just updated to 4.9.1.
